version: '3.8'
services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=apilab'
    ports:
      - '27017:27017'
    volumes:
      - 'mongodb_data:/data/db'

volumes:
  mongodb_data: